### ISSUE TITLE
Missing API calls. 

### ISSUE THREAD

**Issue by n8o** [cablelabs/mse-eme#1]
The docs mention -ck_remote <url> and -ck_json. but none of the drm modules used to create the XML data for MP4Box include these options.

**Comment by greg80303** [comment]
@n8o Previously, the ClearKey PSSH box format was not specified anywhere, so we came up with our own.  These options you mention were to support the two methods of accessing clearkeys (URL to remote server, ClearKeys in PSSH in JSON format) that we designed into the PSSH.  However, [the PSSH box has been completely spec'd now](https://w3c.github.io/encrypted-media/cenc-format.html#common-system), so we no longer need the custom format.  I think I have updated all the relevant documentation and the help strings in the cryptfile generators.  Please let me know if you find things I missed.
